# Generated by Django 4.2.17 on 2024-12-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remembermetoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
