services:
  # Backend service (Python/Django)
  web:
    image: python:3.9
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env    # Use backend .env file
    depends_on:
      - db

  # Frontend service (React/Vite)
  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"  # Added --host for container access
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env   # Use frontend .env file
    depends_on:
      - web

  # Database service (PostgreSQL)
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env    # Use backend .env for DB credentials
    ports:
      - "5432:5432"

volumes:
  postgres_data: